export const companyData = {
  company: [
    {
      section: "COMPANY",
      fields: [
        {
          title: null,
          field_parent: null,
          field_name: "name",
          field_code: "1",
          display_name: "Name",
          field_type: "text",
          order: 1,
          required: true,
          visible: true,
        },
        {
          title: null,
          field_parent: null,
          field_name: "gstin",
          field_code: "2",
          display_name: "GSTIN",
          field_type: "text",
          order: 2,
          required: false,
          visible: false,
        },
        {
          title: null,
          field_parent: null,
          field_name: "contact_info",
          field_code: "3",
          display_name: "Contact Info",
          field_type: "array",
          order: 3,
          required: true,
          visible: true,
        },
        {
          title: null,
          field_parent: "contact_info",
          field_name: "contact_type",
          field_code: "4",
          display_name: "Contact Type",
          field_type: "select",
          order: 4,
          required: true,
          visible: true,
        },
        {
          title: null,
          field_parent: "contact_info",
          field_name: "email",
          field_code: "5",
          display_name: "Email",
          field_type: "email",
          order: 5,
          required: true,
          visible: true,
        },
        {
          title: null,
          field_parent: "contact_info",
          field_name: "mobile_number",
          field_code: "6",
          display_name: "Mobile Number",
          field_type: "number",
          order: 6,
          required: true,
          visible: true,
        },
        {
          title: null,
          field_parent: null,
          field_name: "submit_data",
          field_code: "7",
          display_name: "Submit",
          field_type: "button",
          order: 7,
          required: true,
          visible: true,
        },
      ],
    },
    // {
    //   section: "Today",
    //   fields: [
    //     {
    //       title: null,
    //       field_parent: null,
    //       field_name: "name",
    //       field_code: "1",
    //       display_name: "Name",
    //       field_type: "text",
    //       order: 1,
    //       required: true,
    //       visible: true,
    //     },
    //     {
    //       title: null,
    //       field_parent: null,
    //       field_name: "gstin",
    //       field_code: "2",
    //       display_name: "GSTIN",
    //       field_type: "text",
    //       order: 2,
    //       required: false,
    //       visible: true,
    //     },
    //     {
    //       title: null,
    //       field_parent: null,
    //       field_name: "contact_info",
    //       field_code: "3",
    //       display_name: "Contact Info",
    //       field_type: "array",
    //       order: 3,
    //       required: true,
    //       visible: true,
    //     },
    //     {
    //       title: null,
    //       field_parent: "contact_info",
    //       field_name: "contact_type",
    //       field_code: "4",
    //       display_name: "Contact Type",
    //       field_type: "select",
    //       order: 4,
    //       required: true,
    //       visible: true,
    //     },
    //     {
    //       title: null,
    //       field_parent: "contact_info",
    //       field_name: "email",
    //       field_code: "5",
    //       display_name: "Email",
    //       field_type: "email",
    //       order: 5,
    //       required: true,
    //       visible: true,
    //     },
    //     {
    //       title: null,
    //       field_parent: "contact_info",
    //       field_name: "mobile_number",
    //       field_code: "6",
    //       display_name: "Mobile Number",
    //       field_type: "number",
    //       order: 6,
    //       required: true,
    //       visible: true,
    //     },
    //     {
    //       title: null,
    //       field_parent: null,
    //       field_name: "submit_data",
    //       field_code: "7",
    //       display_name: "Submit",
    //       field_type: "button",
    //       order: 7,
    //       required: true,
    //       visible: true,
    //     },
    //   ],
    // },
  ],
};
